### ISSUE TITLE
Model OutlineServer doesn't exist

### ISSUE THREAD

**Issue by cjhenck** [ASL-19/outline-distribution#1]
While trying to set this up, I hit a roadblock with the following error:

```
  File ".../distribution/views.py", line 25, in <module>
    from distribution.models import Vpnuser, OutlineUser, Issue
  File ".../distribution/models.py", line 16, in <module>
    from server.models import OutlineServer
ModuleNotFoundError: No module named 'server'
```

Seems like the server module isn't included? I can't find it in any of the related repos.

**Comment by AurangZ** [comment]
Added Server app and Preference app. I also updated the README with better instructions to set up your django server.
